default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_videos_development
  username: sakakidai
test:
  <<: *default
  database: rails_videos_test
  username: sakakidai

production:
  <<: *default
  database: rails_videos_production
  username: rails_videos
  password: <%= ENV["RAILS_VIDEOS_DATABASE_PASSWORD"] %>
